# Generated by Django 3.2.6 on 2021-08-26 16:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilmGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Gender',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('year', models.PositiveIntegerField(default=2000, verbose_name='Year')),
                ('review_short', models.TextField(blank=True, null=True, verbose_name='Argument (short)')),
                ('review_large', models.TextField(blank=True, null=True, verbose_name='History (large)')),
                ('trailer_url', models.URLField(blank=True, max_length=150, null=True, verbose_name='Url youtube')),
                ('genres', models.ManyToManyField(related_name='film_genres', to='films.FilmGenre', verbose_name='Genders')),
            ],
            options={
                'verbose_name': 'Movie',
                'ordering': ['title'],
            },
        ),
    ]
