# Generated by Django 3.2.6 on 2021-08-31 15:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('films', '0002_auto_20210826_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.PositiveSmallIntegerField(choices=[(0, 'Stateless'), (1, 'View'), (2, 'I want to see')], default=0)),
                ('favorite', models.BooleanField(default=False)),
                ('note', models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(10)])),
                ('review', models.TextField(null=True)),
                ('favorites', models.IntegerField(default=0, verbose_name='Favorites')),
                ('average_note', models.FloatField(default=0.0, validators=[django.core.validators.MaxValueValidator(10.0)], verbose_name='Average grade')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.film')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['film__title'],
                'unique_together': {('film', 'user')},
            },
        ),
    ]
